config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'order_items/create'
  get 'products/index'
  get 'products/show'
  get 'products/show_all_products'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'categories#index'

  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end

  resources :products, only: :show do
    collection do
      get 'products_index'
    end
  end

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :title, presence: true
  has_many :product_categories
  has_many :products, through: :product_categories
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_many :items, class_name: 'OrderItem'
end

app/models/order_item.rb
# frozen_string_literal: true

class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :title, :price, presence: true
  has_many :product_categories
  has_many :categories, through: :product_categories
  has_many :variants, class_name: 'ProductVariant'
  paginates_per 10
  # has_one_attached :image

  # def thumbnail
  #   image.variant(resize: '200x200').processed
  # end

  mount_uploader :image, AvatarUploader
end

app/models/product_category.rb
# frozen_string_literal: true

class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
# frozen_string_literal: true

class ProductVariant < ApplicationRecord
  belongs_to :product
end

app/models/province.rb
# frozen_string_literal: true

class Province < ApplicationRecord
  has_many :users
end

app/models/shopping_cart.rb
# frozen_string_literal: true

class ShoppingCart
  delegate :sub_total, to: :order

  def initialize(token:)
    @token = token
  end

  def order
    # if order is assigned, it will return that instance.
    # if it is null it will create a new order
    @order ||= Order.find_or_create_by(token: @token, status: 'cart') do |order|
      order.sub_total = 0
    end
  end

  def items_count
    order.items.sum(:quantity)
  end

  def add_item(product_id:, quantity: 1, tax:)
    product = Product.find(product_id)

    order_item = order.items.find_or_initialize_by(
      product_id: product_id
    )

    order_item.price = product.price + (product.price * tax)
    order_item.quantity = quantity

    ActiveRecord::Base.transaction do
      order_item.save
      update_sub_total!
    end
  end

  def update_item(product_id:, quantity:, tax:)
    product = Product.find(product_id)
    order_item = order.items.find_or_initialize_by(
      product_id: product_id
    )
    order_item.price = product.price + (product.price * tax)
    order_item.quantity = quantity
    ActiveRecord::Base.transaction do
      order_item.save
      update_sub_total!
    end
  end

  def remove_item(id:)
    ActiveRecord::Base.transaction do
      order.items.destroy(id)
      update_sub_total!
    end
  end

  private

  def update_sub_total!
    order.sub_total = order.items.sum('quantity * price')
    order.save
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :province
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_cart

  def current_cart
    @current_cart ||= ShoppingCart.new(token: cart_token)
  end
  helper_method :current_cart

  private

  def cart_token
    return @cart_token unless @cart_token.nil?

    # if new session, assign new hash
    session[:cart_token] ||= SecureRandom.hex(8)
    @cart_token = session[:cart_token]
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def index
    @categories = Category.joins(:products).select('categories.*,
                          count(products.id) as products_count')
                          .group('categories.id').order(:title)
  end
end

app/controllers/order_items_controller.rb
# frozen_string_literal: true

class OrderItemsController < ApplicationController
  def index
    @items = current_cart.order.items
  end

  def create
    current_cart.add_item(
      product_id: params[:product_id],
      quantity: params[:quantity],
      tax: current_user.province.tax
    )

    redirect_to cart_path
  end

  def update
    current_cart.update_item(
      product_id: params[:product_id],
      quantity: params[:quantity],
      tax: current_user.province.tax
    )
    redirect_to cart_path
  end

  def destroy
    current_cart.remove_item(id: params[:id])
    redirect_to cart_path
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def new
    @order = current_cart.order
  end

  def create
    @order = current_cart.order

    if @order.update_attributes(order_params.merge(status: 'open'))
      session[:cart_token] = nil
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:first_name, :last_name)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @products = @category.products.includes(:variants).order(:title)
  end

  def show_all_products
    @query = params[:query]

    @query = params[:query].downcase unless @query.nil?

    @all_products = Product.where('lower(title) LIKE ?', "%#{@query}%")
                           .order(:title).page params[:page]
    @new_prod = Product.first(3)
    last_updated_products = Product.order(updated_at: :desc)
    @recent_updates = last_updated_products.first(3)

    if !params[:category_id].nil? && params[:category_id] != '89'
      category = Category.find(params[:category_id])
      @all_products = category.products.where('lower(title) LIKE ?',
                                              "%#{@query}%").order(:title)
                              .page params[:page]
    else
      @all_products = Product.where('lower(title) LIKE ?', "%#{@query}%")
                             .order(:title).page params[:page]
    end
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :address,
                                 :postal_code, :city, :province)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :current_password,
                                 :address, :postal_code, :city, :province)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/order_items_helper.rb
# frozen_string_literal: true

module OrderItemsHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/categories/index.html.erb
Category#index
<h2>Categories (<%= @categories.length %>)</h2>

<ol>
  <% @categories.each do |category| %>
    <li>
      <%= link_to category_products_path(category) do %>
        <%= category.title %>
        (<%= category.products.count %> products)
      <% end %>
    </li>
  <% end %>
</ol>

app/views/order_items/index.html.erb
<h1>OrderItems#index</h1>
<p>Find me in app/views/order_items/index.html.erb</p>

<table class="table">
  <thead>
    <tr>
      <td>Product</td>
      <td>Price</td>
      <td>Quantity</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.product.title %></td>
        <td><%= number_to_currency (item.price / (1 + current_user.province.tax)) %></td>
        <td>
          <%= form_for item do %>
            <%= hidden_field_tag :product_id, item.product_id %>
            <%= number_field_tag :quantity, item.quantity %>
            <%= submit_tag "Update Cart" %>
          <% end %>
        </td>
        <td>
          <%= form_for item, method: :delete do |f| %>
            <%= f.submit "Remove" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <td colspan="4" align="right">
        Subtotal: <%= number_to_currency (current_cart.sub_total / (1 + current_user.province.tax)) %>
      <td>
    </tr>
  </tfoot>
</table>

<%= link_to 'Checkout', checkout_path %>

app/views/orders/new.html.erb
<h2>Checkout</h2>

<% if user_signed_in? %>
  <p>Confirm Details</p>
  <%= form_for @order, url: checkout_path do |f| %>
    <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, :value => current_user.name %>
    </div>
    <p>Address: <%=current_user.address%></p>
    <p>Postal Code: <%=current_user.postal_code%></p>
    <p>City: <%=current_user.city%></p>
    <p>Province: <%=current_user.province.name%></p>
    </br>
    <p>SubTotal: <%= number_to_currency current_cart.sub_total  / (1 + current_user.province.tax) %></p>
    <p>Tax: <%= number_to_currency current_cart.sub_total - (current_cart.sub_total  / (1 + current_user.province.tax))%></p>
    <p>Total = <%= number_to_currency current_cart.sub_total %></p>
    <%= f.submit 'Checkout'%>
  <% end %>
<% else %>
  <%= form_for @order, url: checkout_path do |f| %>
  <div class="form-group">
   <%= f.label :first_name %>
   <%= f.text_field :first_name %>
  </div>

  <div class="form-group">
   <%= f.label :last_name %>
   <%= f.text_field :last_name %>
  </div>

  <%= f.submit 'Checkout'%>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<div class="column is-one-fifth">
  <div class="card products">
    <div class="card-content">
      <p class="title is-4">
        <%= link_to product.title, product %>
      </p>
      <% if product.image.present? %>
        <div class="card-image">
          <figure class="image is-4by3">
            <%= image_tag product.image_url(:medium).to_s %>
          </figure>
        </div>
      <% else %>
        <div class="card-image">
          <figure class="image is-4by3">
            <%= image_tag "https://bulma.io/images/placeholders/1280x960.png" %>
          </figure>
        </div>
      <% end %>
      <div class="content">
          <p><strong>Description</strong><%=product.description%></p>
          <p><strong>Price</strong><%=product.price%></p>
          <p><strong>Stock Quantity</strong><%=product.stock_quantity%></p>
          <p><%=%></p>
          <%= form_tag order_items_path do %>
            <%= hidden_field_tag :product_id, product.id %>
            <%= number_field_tag :quantity, 1 %>
            <%= submit_tag "Add to Cart" %>
          <% end %>
      </div>

    </div>
  </div>
</div>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

<h2>
  <%= link_to "Categories", root_path %> /
  <%= @category.title %> /
  Products
</h2>

<ol>
  <% @products.each do |product| %>
    <li>
      <%= product.title %> (<%= number_to_currency product.price %>)

      <%= form_tag order_items_path do %>
        <%= hidden_field_tag :product_id, product.id %>
        <%= number_field_tag :quantity, 1 %>
        <%= submit_tag "Add to Cart" %>
      <% end %>

      <ul>
        <% product.variants.each do |variant| %>
          <li><%= variant.title %> (<%= number_to_currency variant.price %>)</li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ol>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>
<section class="section">
      <p>
        <%= link_to "Home", root_path %> -
        <%= link_to "All Products", products_show_all_products_path %> -
        <%= link_to pluralize(current_cart.items_count, 'item'), cart_path %>
      </p>

      <%= form_with(url: products_show_all_products_path, method: "get", local: true) do %>
        <%= select_tag "category_id", options_from_collection_for_select(Category.all, "id", "title", '179'), html: {selected: true} %>
        <%= label_tag(:query, "Search for:") %>
        <%= text_field_tag(:query) %>
        <%= submit_tag("Search") %>
      <% end %>
    </section>
<%= render partial: 'product',
            object: @product,
            locals: { name_is_link: false } %>

app/views/products/show_all_products.html.erb
<h1 class="title is-1">Products#show_all_products</h1>
<p>Find me in app/views/products/show_all_products.html.erb</p>
<section class="section">
      <p>
        <%= link_to "Home", root_path %> -
        <%= link_to "All Products", products_show_all_products_path %> -
        <%= link_to pluralize(current_cart.items_count, 'item'), cart_path %>
      </p>

      <%= form_with(url: products_show_all_products_path, method: "get", local: true) do %>
        <%= select_tag "category_id", options_from_collection_for_select(Category.all, "id", "title", '179'), html: {selected: true} %>
        <%= label_tag(:query, "Search for:") %>
        <%= text_field_tag(:query) %>
        <%= submit_tag("Search") %>
      <% end %>
    </section>
<h1 class="title is-1">New Products</h1>
<div class="columns is-multiline">
  <%= render partial: "product", collection: @new_prod %>
</div>

<h1 class="title is-1">Recently Updated</h1>
<div class="columns is-multiline">
  <%= render partial: "product", collection: @recent_updates %>
</div>

<h1 class="title is-1">All Products</h1>
<div class="columns is-multiline">
  <%= render partial: "product", collection: @all_products %>
</div>
<div class="d-inline-block">
  <%= paginate @all_products, window: 2 %>
</div>