config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'registrations'
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'order_items/create'
  get 'products/index'
  get 'products/show'
  get 'products/show_all_products'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'categories#index'

  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end

  resources :products, only: :show do
    collection do
      get 'products_index'
    end
  end

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :title, presence: true
  has_many :product_categories
  has_many :products, through: :product_categories
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_many :items, class_name: 'OrderItem'
end

app/models/order_item.rb
# frozen_string_literal: true

class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :title, :price, presence: true
  has_many :product_categories
  has_many :categories, through: :product_categories
  has_many :variants, class_name: 'ProductVariant'
  paginates_per 10
  # has_one_attached :image

  # def thumbnail
  #   image.variant(resize: '200x200').processed
  # end

  mount_uploader :image, AvatarUploader
end

app/models/product_category.rb
# frozen_string_literal: true

class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
# frozen_string_literal: true

class ProductVariant < ApplicationRecord
  belongs_to :product
end

app/models/province.rb
# frozen_string_literal: true

class Province < ApplicationRecord
  has_many :users
end

app/models/shopping_cart.rb
# frozen_string_literal: true

class ShoppingCart
  delegate :sub_total, to: :order

  def initialize(token:)
    @token = token
  end

  def order
    # if order is assigned, it will return that instance.
    # if it is null it will create a new order
    @order ||= Order.find_or_create_by(token: @token, status: 'cart') do |order|
      order.sub_total = 0
    end
  end

  def items_count
    order.items.sum(:quantity)
  end

  def add_item(product_id:, quantity: 1, tax:)
    product = Product.find(product_id)

    order_item = order.items.find_or_initialize_by(
      product_id: product_id
    )

    order_item.price = product.price + (product.price * tax)
    order_item.quantity = quantity

    ActiveRecord::Base.transaction do
      order_item.save
      update_sub_total!
    end
  end

  def update_item(product_id:, quantity:, tax:)
    product = Product.find(product_id)
    order_item = order.items.find_or_initialize_by(
      product_id: product_id
    )
    order_item.price = product.price + (product.price * tax)
    order_item.quantity = quantity
    ActiveRecord::Base.transaction do
      order_item.save
      update_sub_total!
    end
  end

  def remove_item(id:)
    ActiveRecord::Base.transaction do
      order.items.destroy(id)
      update_sub_total!
    end
  end

  private

  def update_sub_total!
    order.sub_total = order.items.sum('quantity * price')
    order.save
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :province
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :current_cart

  def current_cart
    @current_cart ||= ShoppingCart.new(token: cart_token)
  end
  helper_method :current_cart

  private

  def cart_token
    return @cart_token unless @cart_token.nil?

    # if new session, assign new hash
    session[:cart_token] ||= SecureRandom.hex(8)
    @cart_token = session[:cart_token]
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  def index
    @categories = Category.joins(:products).select('categories.*,
                          count(products.id) as products_count')
                          .group('categories.id').order(:title)
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def new
    @order = current_cart.order
  end

  def create
    @order = current_cart.order

    if @order.update_attributes(order_params.merge(status: 'open'))
      session[:cart_token] = nil
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:first_name, :last_name)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @products = @category.products.includes(:variants).order(:title)
  end

  def show_all_products
    @query = params[:query]

    @query = params[:query].downcase unless @query.nil?

    @all_products = Product.where('lower(title) LIKE ?', "%#{@query}%")
                           .order(:title).page params[:page]
    @new_prod = Product.first(3)
    last_updated_products = Product.order(updated_at: :desc)
    @recent_updates = last_updated_products.first(3)

    if !params[:category_id].nil? && params[:category_id] != '89'
      category = Category.find(params[:category_id])
      @all_products = category.products.where('lower(title) LIKE ?',
                                              "%#{@query}%").order(:title)
                              .page params[:page]
    else
      @all_products = Product.where('lower(title) LIKE ?', "%#{@query}%")
                             .order(:title).page params[:page]
    end
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/helpers/order_items_helper.rb
# frozen_string_literal: true

module OrderItemsHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <%= csrf_meta_tags %>
  </head>
     <body class="<%= yield (:body_class) %>">
      <% if flash[:notice] %>
        <div class="notification is-success global-notification">
          <p class="notice"><%= notice %></p>
        </div>
      <% end %>
      <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
      <% end %>
      <nav id="app" class="navbar is-info" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <%= link_to root_path, class:"navbar-item" do %>
            <h1 class="title is-5">Ecomm Project</h1>
          <% end  %>

          <a role="button" class="navbar-burger burger" v-on:click="showNav = !showNav" v-bind:class="{ 'is-active' : showNav }" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu" v-bind:class="{ 'is-active' : showNav }">

          <div class="navbar-end">
            <div class="navbar-item">

              <% if user_signed_in? %>
                <%= link_to "Home", root_path, class: "navbar-item" %>
                <%= link_to "All Products", products_show_all_products_path, class: "navbar-item is-white" %>
                <%= link_to pluralize(current_cart.items_count, 'item'), cart_path, class: "navbar-item is-white" %>
                <div class="navbar-item has-dropdown is-hoverable">
                  <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
                  <div class="navbar-dropdown is-right">
                    <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>
                    <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                  </div>
                </div>
              <% else %>
                <div class="buttons">
                  <%= link_to "Log In", new_user_session_path, class:" button is-primary" %>
                  <%= link_to "Sign up", new_user_registration_path, class:"button is-light"%>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </nav>

    <%= yield(:header) %>

    <div class="container">
      <%= yield %>
    </div>
    <%= javascript_pack_tag 'nav' %>
  </body>
</html>